### ISSUE TITLE
Problem with path params using subresources

### ISSUE THREAD

**Issue by cyppan** [pyeve/eve-swagger#2]
When using sub-resources (http://python-eve.org/features.html#sub-resources) you probably have this kind of url: `'people/<regex("[a-f0-9]{24}"):contact_id>/invoices'`
This syntax "conflicts" with the Swagger path params which are defined using brackets `{`. Then it considers that `24` is a path params, but not `contact_id`.
I'm not sure what would be the right approach for this problem, maybe rewrite urls to have something like `people/{contact_id}/invoices` and a swagger path definition like

```
{
  "name": "contact_id",
  "in": "path",
  "description": "regex("[a-f0-9]{24}")",
  "required": true,
  "type": "string"
}
```

**Comment by nicolaiarocci** [comment]
Yes sounds like a good plan.

**Comment by pdecat** [comment]
Looks like the proper way to handle those would be to use the `pattern` field to hold the regex instead of `description`:

```
{
  "name": "contact_id",
  "in": "path",
  "pattern": "[a-f0-9]{24}",
  "required": true,
  "type": "string"
}
```

http://stackoverflow.com/a/33711973/316805
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#user-content-parameterPattern
http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.8
